blank_issues_enabled: true
contact_links:
  - name: See the official Board meeting archive
    url: https://multnomah.granicus.com/ViewPublisher.php?view_id=3
    about: Official agendas, minutes and video from the Multnomah County Board of Commissioners.
